version: '3.8'

services:  
  db:
    image: postgres:14.8
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: food_trucks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
